# Cross platform GitHub Actions CI for undeaD

name: Testsuite

# Only triggers on pushes to master & stable, as well as PR to master and stable
# Sometimes reverts appear in the upstream repository (e.g. when the revert button
# is clicked by a contributor with commit access), this should be tested as PR).
#
# Also note that Github actions does not retrigger on target branch changes,
# hence the check on push.
on:
  pull_request:
    branches:
      - master
      - stable
  push:
    branches:
      - master
      - stable
      # Use this branch name in your fork to test changes
      - github-actions

jobs:
  main:
    name: Run
    strategy:
      # Default, disable if you want to debug
      fail-fast: false
      matrix:
        # Latest stable version, update at will
        os: [ macOS-10.15, ubuntu-20.04, windows-2019 ]
        dc: [ dmd-latest, ldc-latest, dmd-master, ldc-master ]

    runs-on: ${{ matrix.os }}
    steps:

    - name: Install D compiler - ${{ matrix.dc }}
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Build and Test'
      shell: bash
      run: |
        $DC --version
        dub build --compiler=$DC
        dub test --compiler=$DC -v
